repos:
  - hooks:
      - id: trailing-whitespace
        args: [ '--markdown-linebreak-ext=md' ]
        exclude: |
            (?x)^(
                .idea/|
                buildrun/docker/main-app/drivers/
            )$
      - id: check-json
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                .idea/|
                buildrun/docker/main-app/drivers/
            )$
      - id: check-added-large-files
        args: [ '--maxkb=10000' ]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - files: requirements.txt
        id: python-safety-dependencies-check
        args: [ '--disable-telemetry' ]
    repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 23.1.0
  - hooks:
      - id: hadolint-docker
    repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
  - hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
    repo: https://github.com/pycqa/isort
    rev: 5.11.5
