{
 "title": "IBMi statuses",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(ibmi_system_cpu_usage_average_ratio{}, server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ibmi_system_status_up{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "ibmi_ecosystem_environment_info{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk storage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmi_system_storage_used_ratio{server=\"$server\", storage_type=\"asp\"} * 100",
     "legendFormat": "ASP"
    },
    {
     "expr": "ibmi_system_storage_used_ratio{server=\"$server\", storage_type=\"auxiliary\"} * 100",
     "legendFormat": "Auxiliary"
    }
   ]
  },
  {
   "title": "CPU utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ibmi_system_cpu_usage_average_ratio{server=\"$server\"}*100",
     "legendFormat": "utilisation_ratio"
    }
   ]
  },
  {
   "title": "Jobs in System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ibmi_system_jobs_max{server=\"$server\"}",
     "legendFormat": "max_jobs_allowed"
    },
    {
     "expr": "ibmi_system_jobs_all_total{server=\"$server\"}",
     "legendFormat": "all_jobs",
     "target": "TOTAL_JOBS_IN_SYSTEM",
     "type": "timeserie"
    },
    {
     "expr": "ibmi_system_jobs_active_total{server=\"$server\"}",
     "legendFormat": "active_jobs",
     "target": "ACTIVE_JOBS_IN_SYSTEM",
     "type": "timeserie"
    },
    {
     "expr": "system_jobs_batch_total{server=\"$server\"}",
     "legendFormat": "batch_jobs"
    }
   ]
  },
  {
   "title": "Number of remote connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "ibmi_remote_connections_total{server=\"$server\"}",
     "legendFormat": "remote_connections"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "ibmi_system_threads_total{server=\"$server\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Status timeline",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ibmi_system_status_up{server=\"$server\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Storage pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pool current size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmi_pool_storage_current_bytes{server=\"$server\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmi_pool_threads_total{server=\"$server\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "HTTP Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Server Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_join(ibmi_http_server_connections_total{server=\"$server\", connections_type=\"normal\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "normal_connections"
    },
    {
     "expr": "label_join(ibmi_http_server_connections_total{server=\"$server\", connections_type=\"ssl\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "ssl_connections"
    },
    {
     "expr": "label_join(ibmi_http_server_requests_total{server=\"$server\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "requests_received"
    },
    {
     "expr": "label_join(ibmi_http_server_responses_total{server=\"$server\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "responses_sent"
    },
    {
     "expr": "label_join(ibmi_http_server_error_responses_total{server=\"$server\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "error_responses_sent"
    },
    {
     "expr": "label_join(ibmi_http_server_bytes_total{server=\"$server\", flow_direction=\"sent\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "bytes_sent"
    },
    {
     "expr": "label_join(ibmi_http_server_bytes_total{server=\"$server\", flow_direction=\"received\"}, \"http_server_function\", \",\", \"http_server\",\"http_function\")",
     "legendFormat": "bytes_received"
    }
   ]
  },
  { "title": "Subsytems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Statuses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "ibmi_subsystem_status{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "ibmi_subsystem_jobs_active_total{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}